services:
  storefront:
    container_name: storefront
    build:
      context: .
      dockerfile: Dockerfile.base
      args:
        - TARGET_APP=storefront
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.storefront-app.rule=Host(`surmont.ro`)"
      - "traefik.http.routers.storefront-app.entrypoints=websecure"
      - "traefik.http.routers.storefront-app.tls=true"
      - "traefik.http.routers.storefront-app.tls.certresolver=cloudflare"
      - "traefik.http.services.storefront-app.loadbalancer.server.port=3000"
      # Add www to non-www redirect
      - "traefik.http.middlewares.to-non-www.redirectregex.regex=^https://www\\.(.+)"
      - "traefik.http.middlewares.to-non-www.redirectregex.replacement=https://$${1}"
      # Chain both middlewares
      - "traefik.http.routers.storefront-app.middlewares=to-non-www,cloudflare-headers"
    networks:
      - saleor-backend-tier
    command: sh -c '(nginx &) && pnpm turbo run start --filter=storefront...'

  products-importer:
    container_name: products-importer
    build:
      context: .
      dockerfile: Dockerfile.base
      args:
        - TARGET_APP=products-importer
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.products-importer.rule=Host(`products-importer.surmont.ro`)"
      - "traefik.http.routers.products-importer.entrypoints=websecure"
      - "traefik.http.routers.products-importer.tls=true"
      - "traefik.http.routers.products-importer.tls.certresolver=cloudflare"
      - "traefik.http.services.products-importer.loadbalancer.server.port=3004"
      - "traefik.http.routers.products-importer.middlewares=cloudflare-headers"
    networks:
      - saleor-backend-tier
    volumes:
      - products-importer-auth-volume:/app/apps/products-importer/apl
    command: sh -c '(nginx &) && pnpm turbo run start --filter=products-importer...'

  manage-promotions:
    container_name: manage-promotions
    build:
      context: .
      dockerfile: Dockerfile.base
      args:
        - TARGET_APP=manage-promotions
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.manage-promotions.rule=Host(`manage-promotions.surmont.ro`)"
      - "traefik.http.routers.manage-promotions.entrypoints=websecure"
      - "traefik.http.routers.manage-promotions.tls=true"
      - "traefik.http.routers.manage-promotions.tls.certresolver=cloudflare"
      - "traefik.http.services.manage-promotions.loadbalancer.server.port=3005"
      - "traefik.http.routers.manage-promotion.middlewares=cloudflare-headers"
    networks:
      - saleor-backend-tier
    volumes:
      - manage-promotions-auth-volume:/app/apps/manage-promotions/apl
    command: sh -c '(nginx &) && pnpm turbo run start --filter=manage-promotions...'

  search:
    container_name: search
    build:
      context: .
      dockerfile: Dockerfile.base
      args:
        - TARGET_APP=search
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.search.rule=Host(`search.surmont.ro`)"
      - "traefik.http.routers.search.entrypoints=websecure"
      - "traefik.http.routers.search.tls=true"
      - "traefik.http.routers.search.tls.certresolver=cloudflare"
      - "traefik.http.services.search.loadbalancer.server.port=3006"
      - "traefik.http.routers.search.middlewares=cloudflare-headers"
    networks:
      - saleor-backend-tier
    volumes:
      - search-auth-volume:/app/apps/search/apl
    command: sh -c '(nginx &) && pnpm turbo run start --filter=search...'

  manage-stock:
    container_name: manage-stock
    build:
      context: .
      dockerfile: Dockerfile.base
      args:
        - TARGET_APP=manage-stock
      labels:
      - "traefik.enable=true"
      - "traefik.http.routers.manage-stock.rule=Host(`manage-stock.surmont.ro`)"
      - "traefik.http.routers.manage-stock.entrypoints=websecure"
      - "traefik.http.routers.manage-stock.tls=true"
      - "traefik.http.routers.manage-stock.tls.certresolver=cloudflare"
      - "traefik.http.services.manage-stock.loadbalancer.server.port=3007"
      - "traefik.http.routers.manage-stock.middlewares=cloudflare-headers"
    networks:
      - saleor-backend-tier
    volumes:
      - manage-stock-auth-volume:/app/apps/manage-stock/apl
      - manage-stock-logs-volume:/app/apps/manage-stock/logs
    command: sh -c '(nginx &) && pnpm turbo run start --filter=manage-stock...'

  smtp:
    container_name: smtp
    build:
      context: .
      dockerfile: Dockerfile.base
      args:
        - TARGET_APP=smtp
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.smtp.rule=Host(`smtp.surmont.ro`)"
      - "traefik.http.routers.smtp.entrypoints=websecure"
      - "traefik.http.routers.smtp.tls=true"
      - "traefik.http.routers.smtp.tls.certresolver=cloudflare"
      - "traefik.http.services.smtp.loadbalancer.server.port=3008"
      - "traefik.http.routers.smtp.middlewares=cloudflare-headers"
    networks:
      - saleor-backend-tier
    volumes:
      - smtp-auth-volume:/app/apps/smtp/apl
    command: sh -c '(nginx &) && pnpm turbo run start --filter=smtp...'

  payment:
    container_name: payment
    build:
      context: .
      dockerfile: Dockerfile.base
      args:
        - TARGET_APP=payment
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.payment.rule=Host(`payment.surmont.ro`)"
      - "traefik.http.routers.payment.entrypoints=websecure"
      - "traefik.http.routers.payment.tls=true"
      - "traefik.http.routers.payment.tls.certresolver=cloudflare"
      - "traefik.http.services.payment.loadbalancer.server.port=3009"
      - "traefik.http.routers.payment.middlewares=cloudflare-headers"
    networks:
      - saleor-backend-tier
    volumes:
      - payment-auth-volume:/app/apps/payment/apl
      - payment-logs-volume:/app/apps/payment/logs
    command: sh -c '(nginx &) && pnpm turbo run start --filter=payment...'

volumes:
  manage-promotions-auth-volume:
  smtp-auth-volume:
  search-auth-volume:
  products-importer-auth-volume:
  manage-stock-auth-volume:
  manage-stock-logs-volume:
  payment-auth-volume:
  payment-logs-volume:

networks:
  saleor-backend-tier:
    external: true