services:
  storefront:
    container_name: storefront
    build:
      context: .
      dockerfile: Dockerfile.base
      args:
        - TARGET_APP=storefront
    ports:
      - 3000:3000
    networks:
      - saleor-backend-tier
    command: sh -c '(nginx &) && pnpm turbo run start --filter=storefront...'
  products-importer:
    container_name: products-importer
    build:
      context: .
      dockerfile: Dockerfile.base
      args:
        - TARGET_APP=products-importer
    ports:
      - 3004:3004
    networks:
      - saleor-backend-tier
    volumes:
      - products-importer-auth-volume:/app/apps/products-importer/apl
    command: sh -c '(nginx &) && pnpm turbo run start --filter=products-importer...'
  manage-promotions:
    container_name: manage-promotions
    build:
      context: .
      dockerfile: Dockerfile.base
      args:
        - TARGET_APP=manage-promotions
    ports:
      - 3005:3005
    networks:
      - saleor-backend-tier
    volumes:
      - manage-promotions-auth-volume:/app/apps/manage-promotions/apl
    command: sh -c '(nginx &) && pnpm turbo run start --filter=manage-promotions...'
  search:
    container_name: search
    build:
      context: .
      dockerfile: Dockerfile.base
      args:
        - TARGET_APP=search
    ports:
      - 3006:3006
    networks:
      - saleor-backend-tier
    volumes:
      - search-auth-volume:/app/apps/search/apl
    command: sh -c '(nginx &) && pnpm turbo run start --filter=search...'
  manage-stock:
    container_name: manage-stock
    build:
      context: .
      dockerfile: Dockerfile.base
      args:
        - TARGET_APP=manage-stock
    ports:
      - 3007:3007
    networks:
      - saleor-backend-tier
    volumes:
      - manage-stock-auth-volume:/app/apps/manage-stock/apl
      - manage-stock-logs-volume:/app/apps/manage-stock/logs
    command: sh -c '(nginx &) && pnpm turbo run start --filter=manage-stock...'
  emails-and-messages:
    container_name: emails-and-messages
    build:
      context: .
      dockerfile: Dockerfile.base
      args:
        - TARGET_APP=emails-and-messages
    ports:
      - 3008:3008
    networks:
      - saleor-backend-tier
    volumes:
      - emails-and-messages-auth-volume:/app/apps/emails-and-messages/apl
    command: sh -c '(nginx &) && pnpm turbo run start --filter=emails-and-messages...'
volumes:
  manage-promotions-auth-volume:
  emails-and-messages-auth-volume:
  search-auth-volume:
  products-importer-auth-volume:
  manage-stock-auth-volume:
  manage-stock-logs-volume:

networks:
  saleor-backend-tier:
    external: true
