query ProductCollection($filter: ProductFilterInput, $channel: String, $first: Int, $after: String) {
  products(first: $first, after: $after, channel: $channel, filter: $filter) {
    edges {
      node {
        id
        isAvailable
        isAvailableForPurchase
        variants {
          sku
          quantityLimitPerCustomer
          stocks {
            warehouse {
              slug
            }
            quantity
          }
        }
      }    
    }
    pageInfo {
      hasNextPage
      endCursor
    }
  }
}