query ProductCollectionFeed(
  $before: String
  $after: String
  $first: Int = 90
  $filter: ProductFilterInput
  $sortBy: ProductOrder
  $channel: String!
  $locale: LanguageCodeEnum!
) {
  products(
    first: $first
    channel: $channel
    after: $after
    before: $before
    filter: $filter
    sortBy: $sortBy
  ) {
    edges {
      cursor
      node {
        ...ProductDetailsFragment
      }
    }
    pageInfo {
      hasNextPage
      hasPreviousPage
      startCursor
      endCursor
    }
  }
}
